project:
  type: website

website:
  title: "On Notes"
  navbar:
    left:
      # - text: "Home"
      #   href: index.qmd
      - text: "About"
        href: about.qmd
  #   right:
  #     - about.qmd
      # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    execute: false
    code-fold: true
    code-summary: "Show the code"
    code-block-border-left: "#31BAE9"
    code-line-numbers: true
    code-link: true
    # theme:
    #   - cosmo
    #   - brand
    # css: styles.css



